print("===== CREADOR DE PERSONAJES =====")

nombre = input("Nombre del personaje: ")
edad = input("Edad: ")
raza = input("Raza: ")
clase = input("Clase (Guerrero, Mago, Arquero, etc.): ")
arma = input("Arma principal: ")
poder = input("Poder especial: ")
nivel = input("Nivel inicial: ")

print("\n===== PERSONAJE CREADO =====")
print("Nombre:", nombre)
print("Edad:", edad)
print("Raza:", raza)
print("Clase:", clase)
print("Arma:", arma)
print("Poder especial:", poder)
print("Nivel:", nivel)
print("\n¡Tu aventura está por comenzar! ⚔️")